# -*- coding: utf-8 -*-
"""gradient_descent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14IpYf81x7gPYTt-e9axhadxLvPksOst2
"""

from sklearn.datasets import fetch_california_housing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


data = fetch_california_housing()

df = pd.DataFrame(data.data, columns=data.feature_names)
df['Price'] = data.target


X=df.drop('Price',axis=1)
y=df['Price']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=42)

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_train_scaled=scaler.transform(X_train)
X_test_scaled=scaler.transform(X_test)


learning_rate=0.01
iterations=1000

w=np.random.randn(X_train.shape[1])
b=np.random.randn()

for i in range(iterations):
  y_pred=X_train_scaled@w+b
  error=y_pred-y_train

  w_grad=X_train_scaled.T@error/X_train.shape[0]
  b_grad=np.mean(error)

  w=w-learning_rate*w_grad
  b=b-learning_rate*b_grad


pred=X_test_scaled@w+b

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

mae=mean_absolute_error(y_test,pred)
mse=mean_squared_error(y_test,pred)
r2=r2_score(y_test,pred)

print("MAE: ",mae)
print("MSE: ",mse)
print("R2:",r2)

print("Weight:",w)
print("bias: ",b)

comparison=pd.DataFrame({
    "Actual":y_test.values,
    "predicted":pred
})

print(comparison.head(10))


plt.scatter(y_test,pred)
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("Actual vs Predicted ")
plt.show()